# Generated by Django 4.2.16 on 2024-12-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transactions",
            "0002_message_alter_transaction_product_delete_product_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="meeting_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
