# Generated by Django 5.1.3 on 2024-12-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_userprofile_department_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(
                default="default@ccmailg.meijo-u.ac.jp", max_length=254, unique=True
            ),
        ),
    ]
