# Generated by Django 5.1.3 on 2024-12-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_userprofile_password_alter_userprofile_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="faculty",
            field=models.CharField(default="未設定", max_length=255),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="grade",
            field=models.CharField(default="未設定", max_length=50),
        ),
    ]
