# Generated by Django 5.1.3 on 2024-12-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_userprofile_faculty_userprofile_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="product_name",
            field=models.CharField(default="未設定", max_length=100),
        ),
    ]
