# Generated by Django 5.1.3 on 2024-12-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_userprofile_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="availability",
            field=models.JSONField(default=list),
        ),
    ]
