# Generated by Django 5.1.3 on 2024-12-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_buyer_product_description"),
        ("products", "0006_userprofile_availability"),
    ]

    operations = []
