# Generated by Django 4.2.16 on 2024-12-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_favorite_created_at'),
        ('products', '0007_merge_20241219_2137'),
    ]

    operations = [
    ]
