# Generated by Django 5.1.3 on 2024-12-20 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_merge_20241220_0115"),
        ("products", "0010_favorite_created_at"),
    ]

    operations = []
